#!/bin/bash

source `dirname ${0}`/_local-hook-exec
echo "  ▶ Check credentials by gitleaks"
gitleaks protect -v -c `dirname ${0}`/gitleaks.toml --staged
RET=$?
if [ $RET -eq 0 ] ;then
    exit 0
else
    exit 1
fi
